name: Build Mac App with Pyinstaller
on: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # 降级到 3.11，这个版本的包兼容性目前是最好的
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # 先不装 sonic-python，只装基础库
          pip install pygame pyinstaller
          
      - name: Compile Sonic Manually
        run: |
          # 既然你仓库里有源码，我们直接用 Mac 自带的 clang 编译出 .so
          # 这样就不需要求助于 pip 了
          gcc -shared -O3 -fPIC sonic.c -o libsonic.so
          
      - name: Build with Pyinstaller
        run: |
          # 把我们现场编译的 libsonic.so 也打进去
          pyinstaller --noconfirm --onedir --windowed \
                      --add-data "SourceHanSansCN-Bold.otf:." \
                      --add-data "config.json:." \
                      --add-data "libsonic.so:." \
                      main.py
                           
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RhythmGame-Mac-Pyinstaller
          path: dist/main.app
